# Site
repository: khhan1993/khhan1993.github.io
favicon: assets/images/logo.png

# Personal info
name: Kihoon Han
title: 한양대학교 한기훈
email: me@hoony9x.com
phone:
website:
blog: https://blog.hoony9x.com

# Social links
twitter_username: khhan1993
github_username:  hoony9x
dribbble_username:
facebook_username: hoony9x
flickr_username:
instagram_username: hoony9x
linkedin_username: kihoon-han-03a801117
xing_username:
pinterest_username:
youtube_username:
googleplus_username:

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/profile_image.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Computer Science student (undergraduate) in Hanyang University, Republic of Korea.<br/>
  I have experience developing web server and managing programming contest system.<br/>

  I am most skilled in: <mark>AWS</mark>, <mark>Node.JS (ExpressJS)</mark>, and <mark>Python3 (Flask)</mark>.

  I am also interested in: <mark>Operating Programming Contest</mark>, and <mark>Photography</mark>.



# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  My other hobbies are:
    - Photography

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
