# Site
name: "Han K.H."
title: "Han K.H."
description: "한양대학교 한기훈"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-142546009-1'
lang: ko_KR
disqus: 'blog-khhan1993-com'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  khhan1993:
    name: Kihoon Han
    display_name: khhan1993
    gravatar: 2091077825c6f093f897ad1c5fe75041
    email: khhan1993@gmail.com
    web: https://khhan1993.com
    twitter: https://www.twitter.com/khhan1993
    facebook: https://www.facebook.com/khhan1993
    linkedin: https://www.linkedin.com/in/kihoon-han-03a801117
    instagram: https://www.instagram.com/com.khhan1993
    description: "한양대학교 한기훈"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page/:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-9940602024600777"
adsense-data-ad-slot-header: "8236148980"
adsense-data-ad-slot-footer: "9438739384"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [LICENSE.txt, README.md, Gemfile, Gemfile.lock]