name: Hexo Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
    - uses: actions/checkout@master

    - name: SETUP_NODE_${{ matrix.node }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}

    - name: BEFORE_INSTALL
      run: npm i -g hexo workbox-cli

    - name: BEFORE_SCRIPT
      run: |
        git config --global user.name 'hoony9x'
        git config --global user.email 'me@hoony9x.com'
        sed -i "s/__GITHUB_TOKEN__/${{ secrets.HEXO_BUILD_AND_DEPLOY_KEY }}/" _config.yml

    - name: THEME_INSTALL
      run: |
        git submodule update --init --remote --recursive

    - name: NPM_INSTALL
      run: npm install

    - name: HEXO_CLEAN
      run: hexo clean

    - name: HEXO_GENERATE
      run: hexo generate

    - name: WORKBOX_BUILD
      run: workbox injectManifest

    - name: HEXO_DEPLOY
      run: hexo deploy